apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: revolut
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: revolut
  template:
    metadata:
      labels:
        app: revolut
    spec:
      containers:
        - name: backend
          image: "androidleha/revolut:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP