name: Deployment

on: [push]

jobs:
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
    AWS_DEFAULT_REGION: us-west-2
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: mvn -B install
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build . --file Dockerfile --tag androidleha/revolut:latest
    - run: docker push androidleha/revolut:latest
#    - run: terraform apply -var 'access_key=${{ secrets.aws_access_key }}' -var 'secret_key=${{ secrets.aws_secret_key }}'
#      working-directory: ./deployment/terraform
#    - run: terraform output kubeconfig > ~/.kube/config
#      working-directory: ./deployment/terraform
#    - run: helm init
#      working-directory: ./deployment/app
#    - run: helm install .
#      working-directory: ./deployment/app


